//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orsimu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Felhaszn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Felhaszn()
        {
            this.Karakter = new HashSet<Karakter>();
        }
    
        public int Felhaszn_Id { get; set; }
        public string Felhaszn_nev { get; set; }
        public string jelszo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karakter> Karakter { get; set; }
    }
}
