//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orsimu
{
    using System;
    using System.Collections.Generic;
    
    public partial class i_fegyver
    {
        public int Id { get; set; }
        public int invertory_Id { get; set; }
        public int fegyver_id { get; set; }
    
        public virtual Fegyver Fegyver { get; set; }
        public virtual invertory invertory { get; set; }
    }
}
