//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orsimu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karakter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Karakter()
        {
            this.invertory = new HashSet<invertory>();
        }
    
        public int kar_Id { get; set; }
        public string kar_nev { get; set; }
        public Nullable<int> max_elet { get; set; }
        public int akt_elet { get; set; }
        public int tamadas { get; set; }
        public int vedes { get; set; }
        public int gyorsasag { get; set; }
        public int felhaszn_id { get; set; }
        public int oraber { get; set; }
        public int penz { get; set; }
        public int talonpenz { get; set; }
        public Nullable<int> akt_fegyver { get; set; }
    
        public virtual Felhaszn Felhaszn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invertory> invertory { get; set; }
    }
}
