//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class lenyek
    {
        public int Id { get; set; }
        public Nullable<int> maxelet { get; set; }
        public Nullable<int> aktelet { get; set; }
        public Nullable<int> tamadas { get; set; }
        public Nullable<int> vedes { get; set; }
        public Nullable<int> gyorsasag { get; set; }
        public string nev { get; set; }
    }
}
