//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrSzimulator2000
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karakterek
    {
        public int KarakterId { get; set; }
        public string Nev { get; set; }
        public int Tamadas { get; set; }
        public int Vedes { get; set; }
    }
}
